/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivitesRouteImport } from './routes/activites'
import { Route as DestinationRouteImport } from './routes/destination'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ChambresIndexRouteImport } from './routes/chambres.index'
import { Route as ChambresSlugRouteImport } from './routes/chambres.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitesRoute = ActivitesRouteImport.update({
  id: '/activites',
  path: '/activites',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationRoute = DestinationRouteImport.update({
  id: '/destination',
  path: '/destination',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ChambresIndexRoute = ChambresIndexRouteImport.update({
  id: '/chambres/',
  path: '/chambres/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChambresSlugRoute = ChambresSlugRouteImport.update({
  id: '/chambres/$slug',
  path: '/chambres/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activites': typeof ActivitesRoute
  '/destination': typeof DestinationRoute
  '/services': typeof ServicesRoute
  '/chambres/$slug': typeof ChambresSlugRoute
  '/chambres/': typeof ChambresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activites': typeof ActivitesRoute
  '/destination': typeof DestinationRoute
  '/services': typeof ServicesRoute
  '/chambres/$slug': typeof ChambresSlugRoute
  '/chambres': typeof ChambresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activites': typeof ActivitesRoute
  '/destination': typeof DestinationRoute
  '/services': typeof ServicesRoute
  '/chambres/$slug': typeof ChambresSlugRoute
  '/chambres/': typeof ChambresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activites'
    | '/destination'
    | '/services'
    | '/chambres/$slug'
    | '/chambres/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activites'
    | '/destination'
    | '/services'
    | '/chambres/$slug'
    | '/chambres'
  id:
    | '__root__'
    | '/'
    | '/activites'
    | '/destination'
    | '/services'
    | '/chambres/$slug'
    | '/chambres/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitesRoute: typeof ActivitesRoute
  DestinationRoute: typeof DestinationRoute
  ServicesRoute: typeof ServicesRoute
  ChambresSlugRoute: typeof ChambresSlugRoute
  ChambresIndexRoute: typeof ChambresIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activites': {
      id: '/activites'
      path: '/activites'
      fullPath: '/activites'
      preLoaderRoute: typeof ActivitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destination': {
      id: '/destination'
      path: '/destination'
      fullPath: '/destination'
      preLoaderRoute: typeof DestinationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chambres/': {
      id: '/chambres/'
      path: '/chambres'
      fullPath: '/chambres/'
      preLoaderRoute: typeof ChambresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chambres/$slug': {
      id: '/chambres/$slug'
      path: '/chambres/$slug'
      fullPath: '/chambres/$slug'
      preLoaderRoute: typeof ChambresSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitesRoute: ActivitesRoute,
  DestinationRoute: DestinationRoute,
  ServicesRoute: ServicesRoute,
  ChambresSlugRoute: ChambresSlugRoute,
  ChambresIndexRoute: ChambresIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
